package org.mozilla.fenix.GleanMetrics
import java.util.Calendar
import mozilla.components.service.glean.BuildInfo
import org.mozilla.fenix.MetricStub
import org.mozilla.fenix.MapStub

object ReviewPrompt {
    @JvmStatic fun submit(value: Any? = null) {}    @JvmStatic fun submit() {}
    @JvmField val accessPoint = MapStub()
    @JvmField val kills = MapStub()
    @JvmField val record = MetricStub()
    @JvmField val set = MetricStub()
    @JvmField val add = MetricStub()
    @JvmField val accessibilityServices = MetricStub()
    @JvmField val activation = MetricStub()
    @JvmField val activationId = MetricStub()
    @JvmField val adjustAdGroup = MetricStub()
    @JvmField val adjustCampaign = MetricStub()
    @JvmField val adjustCreative = MetricStub()
    @JvmField val adjustNetwork = MetricStub()
    @JvmField val appBytes = MetricStub()
    @JvmField val applicationOnCreate = MetricStub()
    @JvmField val autoCloseSeen = MetricStub()
    @JvmField val bookmarksSuggestion = MetricStub()
    @JvmField val browsingHistorySuggestion = MetricStub()
    @JvmField val cacheBytes = MetricStub()
    @JvmField val click = MetricStub()
    @JvmField val clipboardSuggestionsEnabled = MetricStub()
    @JvmField val closeAllTabs = MetricStub()
    @JvmField val closeTabSetting = MetricStub()
    @JvmField val contextId = MetricStub()
    @JvmField val copyUrlTapped = MetricStub()
    @JvmField val dataDirBytes = MetricStub()
    @JvmField val defaultBrowser = MetricStub()
    @JvmField val defaultBrowserChanged = MetricStub()
    @JvmField val defaultMozBrowser = MetricStub()
    @JvmField val defaultWallpaper = MetricStub()
    @JvmField val desktopBookmarksCount = MetricStub()
    @JvmField val distributionId = MetricStub()
    @JvmField val enabled = MetricStub()
    @JvmField val enabledAddons = MetricStub()
    @JvmField val enhancedTrackingProtection = MetricStub()
    @JvmField val enterMultiselectMode = MetricStub()
    @JvmField val etpCustomCookiesSelection = MetricStub()
    @JvmField val etpTrackerList = MetricStub()
    @JvmField val foregroundMetrics = MetricStub()
    @JvmField val formDataFailure = MetricStub()
    @JvmField val hasDesktopBookmarks = MetricStub()
    @JvmField val hasEnabledAddons = MetricStub()
    @JvmField val hasInactiveTabs = MetricStub()
    @JvmField val hasInstalledAddons = MetricStub()
    @JvmField val hasMobileBookmarks = MetricStub()
    @JvmField val hasOpenTabs = MetricStub()
    @JvmField val hasRecentPwas = MetricStub()
    @JvmField val hasTopSites = MetricStub()
    @JvmField val identifier = MetricStub()
    @JvmField val impression = MetricStub()
    @JvmField val inactiveTabsCount = MetricStub()
    @JvmField val inactiveTabsEnabled = MetricStub()
    @JvmField val installSource = MetricStub()
    @JvmField val installedAddons = MetricStub()
    @JvmField val jumpBackIn = MetricStub()
    @JvmField val killBackgroundAge = MetricStub()
    @JvmField val killForegroundAge = MetricStub()
    @JvmField val marketingNotificationAllowed = MetricStub()
    @JvmField val mediaPause = MetricStub()
    @JvmField val mediaPlay = MetricStub()
    @JvmField val mobileBookmarksCount = MetricStub()
    @JvmField val mostVisitedSites = MetricStub()
    @JvmField val mozillaProducts = MetricStub()
    @JvmField val normalAndPrivateUriCount = MetricStub()
    @JvmField val notificationsAllowed = MetricStub()
    @JvmField val openLinksInAppEnabled = MetricStub()
    @JvmField val openingScreen = MetricStub()
    @JvmField val panelSettings = MetricStub()
    @JvmField val queryStatsDuration = MetricStub()
    @JvmField val recentlySaved = MetricStub()
    @JvmField val recentlyUsedPwaCount = MetricStub()
    @JvmField val recentlyVisited = MetricStub()
    @JvmField val remoteDebuggingEnabled = MetricStub()
    @JvmField val searchShortcutsEnabled = MetricStub()
    @JvmField val searchSuggestionsEnabled = MetricStub()
    @JvmField val searchWidgetInstalled = MetricStub()
    @JvmField val shareAllTabs = MetricStub()
    @JvmField val shown = MetricStub()
    @JvmField val signedInSync = MetricStub()
    @JvmField val studiesEnabled = MetricStub()
    @JvmField val supported = MetricStub()
    @JvmField val syncItems = MetricStub()
    @JvmField val tabViewSetting = MetricStub()
    @JvmField val tabsOpenCount = MetricStub()
    @JvmField val telemetryEnabled = MetricStub()
    @JvmField val toolbarPosition = MetricStub()
    @JvmField val toolbarPositionSetting = MetricStub()
    @JvmField val topSitesCount = MetricStub()
    @JvmField val userTheme = MetricStub()
    @JvmField val visitedError = MetricStub()
    @JvmField val voiceButton = MetricStub()
    @JvmField val voiceSearchEnabled = MetricStub()
    @JvmField val welcomeCardImpression = MetricStub()
    @JvmField val welcomeCloseClicked = MetricStub()
    @JvmField val welcomeGetStartedClicked = MetricStub()
    class AppOpenedExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class MetricsExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class OpenedLinkExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class EnteredUrlExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class VisitedErrorExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class SaveLoginsSettingChangedExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class LearnMoreLinkClickExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class WallpaperSelectedExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class OnboardingClosedExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class SettingChangedExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class ShareSelectedTabsExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class SelectedTabsToCollectionExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class BookmarkSelectedTabsExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class CloseSelectedTabsExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class OpenedExistingTabExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class OpenedItemExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class SelectedExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class EngineSelectedExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class PromptAttemptExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class MalformedExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class OpenAddonInToolbarMenuExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class ItemTappedExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class PromptShownExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class PermissionsAllowedExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class PermissionsDeniedExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class PerformedSearchExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class SaveButtonExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class BrowserMenuActionExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class MessageDismissedExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class MessageShownExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class MessageExpiredExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class MessageClickedExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class ForegroundMetricsExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class PreferenceToggledExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class TabViewChangedExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class EtpSettingChangedExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class HomeRecsSpocShownExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class HomeRecsCategoryClickedExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class HomeRecsStoryClickedExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class HomeRecsSpocClickedExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class RecentSearchesTappedExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class HasInactiveTabsExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
    class EnterMultiselectModeExtra(val actionUuid: Any? = null, val autocomplete: Any? = null, val backgroundActiveTabs: Any? = null, val backgroundCrashedTabs: Any? = null, val backgroundTotalTabs: Any? = null, val category: Any? = null, val count: Any? = null, val foregroundActiveTabs: Any? = null, val foregroundCrashedTabs: Any? = null, val foregroundTotalTabs: Any? = null, val messageKey: Any? = null, val name: Any? = null, val reason: Any? = null, val source: Any? = null, val tabCount: Any? = null, val timeInBackground: Any? = null, val timestamp: Any? = null, val url: Any? = null, val value: Any? = null, vararg args: Any?) { fun record() {} }
}
