// This file was autogenerated by some hot garbage in the `nimbus-fml` crate.
// Trust me, you don't want to mess with it!
package org.mozilla.fenix.nimbus
import android.content.Context
import org.mozilla.experiments.nimbus.FeaturesInterface
import org.mozilla.experiments.nimbus.NullVariables
import org.mozilla.experiments.nimbus.Res
import org.mozilla.experiments.nimbus.StringHolder
import org.mozilla.experiments.nimbus.Variables
import org.mozilla.experiments.nimbus.internal.FeatureHolder
import org.mozilla.experiments.nimbus.internal.mapKeysNotNull
import org.mozilla.experiments.nimbus.internal.mapValuesNotNull
import org.mozilla.experiments.nimbus.internal.mergeWith
import org.mozilla.fenix.R

/**
 * An object for safely accessing feature configuration from Nimbus.
 *
 * This is generated.
 *
 * Before use to configure the application or any of its features, this class needs
 * to be wired up to the SDK API. This is an object created by the application which connects to
 * the Nimbus SDK and thence to the server.
 *
 * ```
 * val nimbus: Nimbus = connectToNimbusSDK()
 * FxNimbus.initialize(getSdk = { nimbus })
 * ```
 *
 * Once initialized, this can be used to access typesafe configuration object via the `features` member.
 *
 * This class should not be edited manually, but changed by editing the `nimbus.fml.yaml` file, and
 * re-running the `nimbus-fml` tool, which is likely already being used by the build script.
 */
object FxNimbus {
    class Features {
        /** 
         * Configuration of the Nimbus System in Fenix.
         * 
         */
        val nimbusSystem: FeatureHolder<NimbusSystem> by lazy {
            FeatureHolder(FxNimbus.getSdk, "nimbus-system") { variables ->
                NimbusSystem(variables)
            }
        }
        /** 
         * Features for cookie banner handling.
         */
        val cookieBanners: FeatureHolder<CookieBanners> by lazy {
            FeatureHolder(FxNimbus.getSdk, "cookie-banners") { variables ->
                CookieBanners(variables)
            }
        }
        /** 
         * A feature that does not correspond to an application feature suitable
         * for showing that Nimbus is working. This should never be used in
         * production.
         */
        val nimbusValidation: FeatureHolder<NimbusValidation> by lazy {
            FeatureHolder(FxNimbus.getSdk, "nimbus-validation") { variables ->
                NimbusValidation(variables)
            }
        }
        /** 
         * A feature allowing the grouping of URLs around the search term that
         * it came from.
         */
        val searchTermGroups: FeatureHolder<SearchTermGroups> by lazy {
            FeatureHolder(FxNimbus.getSdk, "search-term-groups") { variables ->
                SearchTermGroups(variables)
            }
        }
        /** 
         * A feature allowing user to easily search for specified results
         * directly in the search bar.
         */
        val unifiedSearch: FeatureHolder<UnifiedSearch> by lazy {
            FeatureHolder(FxNimbus.getSdk, "unified-search") { variables ->
                UnifiedSearch(variables)
            }
        }
        /** 
         * A feature that shows the re-enagement notification if the user is
         * inactive.
         */
        val reEngagementNotification: FeatureHolder<ReEngagementNotification> by lazy {
            FeatureHolder(FxNimbus.getSdk, "re-engagement-notification") { variables ->
                ReEngagementNotification(variables)
            }
        }
        /** 
         * Features for MR 2022.
         */
        val mr2022: FeatureHolder<Mr2022> by lazy {
            FeatureHolder(FxNimbus.getSdk, "mr2022") { variables ->
                Mr2022(variables)
            }
        }
        /** 
         * A feature that configures the new user onboarding page. Note that
         * onboarding is a **first run** feature, and should only be modified by
         * first run experiments.
         */
        val onboarding: FeatureHolder<Onboarding> by lazy {
            FeatureHolder(FxNimbus.getSdk, "onboarding") { variables ->
                Onboarding(variables)
            }
        }
        /** 
         * A feature that shows the pre-permission notification prompt.
         */
        val prePermissionNotificationPrompt: FeatureHolder<PrePermissionNotificationPrompt> by lazy {
            FeatureHolder(FxNimbus.getSdk, "pre-permission-notification-prompt") { variables ->
                PrePermissionNotificationPrompt(variables)
            }
        }
        /** 
         * The homescreen that the user goes to when they press home or new tab.
         */
        val homescreen: FeatureHolder<Homescreen> by lazy {
            FeatureHolder(FxNimbus.getSdk, "homescreen") { variables ->
                Homescreen(variables)
            }
        }
        /** 
         * Configuration for the messaging system.
         * 
         * In practice this is a set of growable lookup tables for the
         * message controller to piece together.
         * 
         */
        val messaging: FeatureHolder<Messaging> by lazy {
            FeatureHolder(FxNimbus.getSdk, "messaging") { variables ->
                Messaging(variables)
            }
        }
        /** 
         * A feature measuring campaign growth data
         */
        val growthData: FeatureHolder<GrowthData> by lazy {
            FeatureHolder(FxNimbus.getSdk, "growth-data") { variables ->
                GrowthData(variables)
            }
        }
    }

    /**
     * This method should be called as early in the startup sequence of the app as possible.
     * This is to connect the Nimbus SDK (and thus server) with the `FxNimbus`
     * class.
     *
     * The lambda MUST be threadsafe in its own right.
     */
    public fun initialize(getSdk: () -> FeaturesInterface?) {
        this.getSdk = getSdk
        this.features.nimbusSystem.withSdk(getSdk)
        this.features.cookieBanners.withSdk(getSdk)
        this.features.nimbusValidation.withSdk(getSdk)
        this.features.searchTermGroups.withSdk(getSdk)
        this.features.unifiedSearch.withSdk(getSdk)
        this.features.reEngagementNotification.withSdk(getSdk)
        this.features.mr2022.withSdk(getSdk)
        this.features.onboarding.withSdk(getSdk)
        this.features.prePermissionNotificationPrompt.withSdk(getSdk)
        this.features.homescreen.withSdk(getSdk)
        this.features.messaging.withSdk(getSdk)
        this.features.growthData.withSdk(getSdk)
        this.reinitialize()
    }

    private var getSdk: () -> FeaturesInterface? = {
        this.api
    }

    /**
     * This is the connection between the Nimbus SDK (and thus the Nimbus server) and the generated code.
     *
     * This is no longer the recommended way of doing this, and will be removed in future releases.
     *
     * The recommended method is to use the `initialize(getSdk)` method, much earlier in the application
     * startup process.
     */
    public var api: FeaturesInterface? = null

    /**
     * Refresh the cache of configuration objects.
     *
     * For performance reasons, the feature configurations are constructed once then cached.
     * This method is to clear that cache for all features configured with Nimbus.
     *
     * It must be called whenever the Nimbus SDK finishes the `applyPendingExperiments()` method.
     */
    public fun invalidateCachedValues() {
        features.nimbusSystem.withCachedValue(null)
        features.cookieBanners.withCachedValue(null)
        features.nimbusValidation.withCachedValue(null)
        features.searchTermGroups.withCachedValue(null)
        features.unifiedSearch.withCachedValue(null)
        features.reEngagementNotification.withCachedValue(null)
        features.mr2022.withCachedValue(null)
        features.onboarding.withCachedValue(null)
        features.prePermissionNotificationPrompt.withCachedValue(null)
        features.homescreen.withCachedValue(null)
        features.messaging.withCachedValue(null)
        features.growthData.withCachedValue(null)
    }

    /**
     * Accessor object for generated configuration classes extracted from Nimbus, with built-in
     * default values.
     */
    val features = Features()

    /**
     * All generated initialization code. Clients shouldn't need to override or call
     * this.
     * We put it in a separate method because we have to be quite careful about what order
     * the initialization happens in— e.g. when importing other FML files.
     */
    private fun reinitialize() {
        // Nothing left to do.
    }
}

// Public interface members begin here.

/** 
 * Configuration of the Nimbus System in Fenix.
 * 
 */
public class NimbusSystem
    private constructor(
      private val _variables: Variables,
      private val _defaults: Defaults) {
   
   private data class Defaults(
      val refreshIntervalForeground: Int
   )

   constructor(_variables: Variables = NullVariables.instance, 
      refreshIntervalForeground: Int = 60
   ) : this(
      _variables = _variables,
      _defaults = Defaults(refreshIntervalForeground = refreshIntervalForeground )
   )

   
   /** 
     * The minimum interval in minutes between fetching experiment
     * recipes in the foreground.
     * 
     */
   val refreshIntervalForeground: Int by lazy {
      _variables.getInt("refresh-interval-foreground") ?: _defaults.refreshIntervalForeground
   }


}

/** 
 * Features for cookie banner handling.
 */
public class CookieBanners
    private constructor(
      private val _variables: Variables,
      private val _defaults: Defaults) {
   
   private data class Defaults(
      val sectionsEnabled: Map<CookieBannersSection, Int>
   )

   constructor(_variables: Variables = NullVariables.instance, 
      sectionsEnabled: Map<CookieBannersSection, Int> = mapOf(CookieBannersSection.DIALOG_RE_ENGAGE_TIME to 4, CookieBannersSection.DIALOG_TEXT_VARIANT to 0, CookieBannersSection.FEATURE_SETTING_VALUE to 0, CookieBannersSection.FEATURE_UI to 1)
   ) : this(
      _variables = _variables,
      _defaults = Defaults(sectionsEnabled = sectionsEnabled )
   )

   
   /** 
     * This property provides a lookup table of whether or not the given section
     * should be enabled.
     */
   val sectionsEnabled: Map<CookieBannersSection, Int> by lazy {
      _variables.getIntMap("sections-enabled")?.mapKeysNotNull(CookieBannersSection::enumValue)?.mergeWith(_defaults.sectionsEnabled) ?: _defaults.sectionsEnabled
   }


}

/** 
 * A feature that does not correspond to an application feature suitable for
 * showing that Nimbus is working. This should never be used in production.
 */
public class NimbusValidation
    private constructor(
      private val _variables: Variables,
      private val _defaults: Defaults) {
   
   private data class Defaults(
      val settingsIcon: String,
      val settingsPunctuation: String,
      val settingsTitle: StringHolder
   )

   constructor(_variables: Variables = NullVariables.instance, 
      settingsIcon: String = "mozac_ic_settings",
      settingsPunctuation: String = "",
      settingsTitle: StringHolder = Res.string(R.string.browser_menu_settings)
   ) : this(
      _variables = _variables,
      _defaults = Defaults(settingsIcon = settingsIcon, settingsPunctuation = settingsPunctuation, settingsTitle = settingsTitle )
   )

   
   /** 
     * The drawable displayed in the app menu for Settings
     */
   val settingsIcon: String by lazy {
      _variables.getString("settings-icon") ?: _defaults.settingsIcon
   }

   /** 
     * The emoji displayed in the Settings screen title.
     */
   val settingsPunctuation: String by lazy {
      _variables.getString("settings-punctuation") ?: _defaults.settingsPunctuation
   }

   /** 
     * The title of displayed in the Settings screen and app menu.
     */
   val settingsTitle: String by lazy {
      _variables.getText("settings-title") ?: _defaults.settingsTitle.toString(_variables.context)
   }


}

/** 
 * A feature allowing the grouping of URLs around the search term that it came
 * from.
 */
public class SearchTermGroups
    private constructor(
      private val _variables: Variables,
      private val _defaults: Defaults) {
   
   private data class Defaults(
      val enabled: Boolean
   )

   constructor(_variables: Variables = NullVariables.instance, 
      enabled: Boolean = true
   ) : this(
      _variables = _variables,
      _defaults = Defaults(enabled = enabled )
   )

   
   /** 
     * If true, the feature shows up on the homescreen and on the new tab
     * screen.
     */
   val enabled: Boolean by lazy {
      _variables.getBool("enabled") ?: _defaults.enabled
   }


}

/** 
 * A feature allowing user to easily search for specified results directly in
 * the search bar.
 */
public class UnifiedSearch
    private constructor(
      private val _variables: Variables,
      private val _defaults: Defaults) {
   
   private data class Defaults(
      val enabled: Boolean
   )

   constructor(_variables: Variables = NullVariables.instance, 
      enabled: Boolean = false
   ) : this(
      _variables = _variables,
      _defaults = Defaults(enabled = enabled )
   )

   
   /** 
     * If true, the feature shows up in the search bar.
     */
   val enabled: Boolean by lazy {
      _variables.getBool("enabled") ?: _defaults.enabled
   }


}

/** 
 * A feature that shows the re-enagement notification if the user is inactive.
 */
public class ReEngagementNotification
    private constructor(
      private val _variables: Variables,
      private val _defaults: Defaults) {
   
   private data class Defaults(
      val enabled: Boolean
   )

   constructor(_variables: Variables = NullVariables.instance, 
      enabled: Boolean = true
   ) : this(
      _variables = _variables,
      _defaults = Defaults(enabled = enabled )
   )

   
   /** 
     * If true, the re-engagement notification is shown to the inactive user.
     */
   val enabled: Boolean by lazy {
      _variables.getBool("enabled") ?: _defaults.enabled
   }


}

/** 
 * Features for MR 2022.
 */
public class Mr2022
    private constructor(
      private val _variables: Variables,
      private val _defaults: Defaults) {
   
   private data class Defaults(
      val sectionsEnabled: Map<Mr2022Section, Boolean>
   )

   constructor(_variables: Variables = NullVariables.instance, 
      sectionsEnabled: Map<Mr2022Section, Boolean> = mapOf(Mr2022Section.HOME_ONBOARDING_DIALOG_EXISTING_USERS to true, Mr2022Section.JUMP_BACK_IN_CFR to true, Mr2022Section.SYNC_CFR to true, Mr2022Section.TCP_CFR to false, Mr2022Section.TCP_FEATURE to false, Mr2022Section.WALLPAPERS_SELECTION_TOOL to true)
   ) : this(
      _variables = _variables,
      _defaults = Defaults(sectionsEnabled = sectionsEnabled )
   )

   
   /** 
     * This property provides a lookup table of whether or not the given section
     * should be enabled.
     */
   val sectionsEnabled: Map<Mr2022Section, Boolean> by lazy {
      _variables.getBoolMap("sections-enabled")?.mapKeysNotNull(Mr2022Section::enumValue)?.mergeWith(_defaults.sectionsEnabled) ?: _defaults.sectionsEnabled
   }


}

/** 
 * A feature that configures the new user onboarding page. Note that onboarding
 * is a **first run** feature, and should only be modified by first run
 * experiments.
 */
public class Onboarding
    private constructor(
      private val _variables: Variables,
      private val _defaults: Defaults) {
   
   private data class Defaults(
      val order: List<OnboardingPanel>
   )

   constructor(_variables: Variables = NullVariables.instance, 
      order: List<OnboardingPanel> = listOf(OnboardingPanel.THEMES, OnboardingPanel.TOOLBAR_PLACEMENT, OnboardingPanel.SYNC, OnboardingPanel.TCP, OnboardingPanel.PRIVACY_NOTICE)
   ) : this(
      _variables = _variables,
      _defaults = Defaults(order = order )
   )

   
   /** 
     * Determines the order of the onboarding page panels
     */
   val order: List<OnboardingPanel> by lazy {
      _variables.getStringList("order")?.mapNotNull(OnboardingPanel::enumValue) ?: _defaults.order
   }


}

/** 
 * A feature that shows the pre-permission notification prompt.
 */
public class PrePermissionNotificationPrompt
    private constructor(
      private val _variables: Variables,
      private val _defaults: Defaults) {
   
   private data class Defaults(
      val enabled: Boolean
   )

   constructor(_variables: Variables = NullVariables.instance, 
      enabled: Boolean = true
   ) : this(
      _variables = _variables,
      _defaults = Defaults(enabled = enabled )
   )

   
   /** 
     * if true, the pre-permission notification prompt is shown to the user.
     */
   val enabled: Boolean by lazy {
      _variables.getBool("enabled") ?: _defaults.enabled
   }


}

/** 
 * The homescreen that the user goes to when they press home or new tab.
 */
public class Homescreen
    private constructor(
      private val _variables: Variables,
      private val _defaults: Defaults) {
   
   private data class Defaults(
      val sectionsEnabled: Map<HomeScreenSection, Boolean>
   )

   constructor(_variables: Variables = NullVariables.instance, 
      sectionsEnabled: Map<HomeScreenSection, Boolean> = mapOf(HomeScreenSection.JUMP_BACK_IN to true, HomeScreenSection.POCKET to true, HomeScreenSection.POCKET_SPONSORED_STORIES to true, HomeScreenSection.RECENT_EXPLORATIONS to true, HomeScreenSection.RECENTLY_SAVED to true, HomeScreenSection.TOP_SITES to true)
   ) : this(
      _variables = _variables,
      _defaults = Defaults(sectionsEnabled = sectionsEnabled )
   )

   
   /** 
     * This property provides a lookup table of whether or not the given section
     * should be enabled. If the section is enabled, it should be toggleable in
     * the settings screen, and on by default.
     */
   val sectionsEnabled: Map<HomeScreenSection, Boolean> by lazy {
      _variables.getBoolMap("sections-enabled")?.mapKeysNotNull(HomeScreenSection::enumValue)?.mergeWith(_defaults.sectionsEnabled) ?: _defaults.sectionsEnabled
   }


}

/** 
 * Configuration for the messaging system.
 * 
 * In practice this is a set of growable lookup tables for the
 * message controller to piece together.
 * 
 */
public class Messaging
    private constructor(
      private val _variables: Variables,
      private val _defaults: Defaults) {
   
   private data class Defaults(
      val actions: Map<String, String>,
      val messageUnderExperiment: String?,
      val messages: Map<String, MessageData>,
      val notificationConfig: NotificationConfig,
      val onControl: ControlMessageBehavior,
      val styles: Map<String, StyleData>,
      val triggers: Map<String, String>
   )

   constructor(_variables: Variables = NullVariables.instance, 
      actions: Map<String, String> = mapOf("ENABLE_PRIVATE_BROWSING" to "://enable_private_browsing", "INSTALL_SEARCH_WIDGET" to "://install_search_widget", "MAKE_DEFAULT_BROWSER" to "://make_default_browser", "OPEN_SETTINGS" to "://settings", "OPEN_SETTINGS_ACCESSIBILITY" to "://settings_accessibility", "OPEN_SETTINGS_ADDON_MANAGER" to "://settings_addon_manager", "OPEN_SETTINGS_DELETE_BROWSING_DATA" to "://settings_delete_browsing_data", "OPEN_SETTINGS_LOGINS" to "://settings_logins", "OPEN_SETTINGS_NOTIFICATIONS" to "://settings_notifications", "OPEN_SETTINGS_PRIVACY" to "://settings_privacy", "OPEN_SETTINGS_SEARCH_ENGINE" to "://settings_search_engine", "OPEN_SETTINGS_TRACKING_PROTECTION" to "://settings_tracking_protection", "OPEN_SETTINGS_WALLPAPERS" to "://settings_wallpapers", "TURN_ON_SYNC" to "://turn_on_sync", "VIEW_BOOKMARKS" to "://urls_bookmarks", "VIEW_COLLECTIONS" to "://home_collections", "VIEW_HISTORY" to "://urls_history", "VIEW_HOMESCREEN" to "://home"),
      messageUnderExperiment: String? = null,
      messages: Map<String, MessageData> = mapOf("default-browser" to MessageData(action = Res.string("MAKE_DEFAULT_BROWSER"), buttonLabel = Res.string(R.string.preferences_set_as_default_browser), style = "PERSISTENT", surface = MessageSurfaceId.HOMESCREEN, text = Res.string(R.string.default_browser_experiment_card_text), trigger = listOf("I_AM_NOT_DEFAULT_BROWSER", "USER_ESTABLISHED_INSTALL")), "default-browser-notification" to MessageData(action = Res.string("MAKE_DEFAULT_BROWSER"), style = "NOTIFICATION", surface = MessageSurfaceId.NOTIFICATION, text = Res.string(R.string.default_browser_experiment_card_text), title = Res.string(R.string.preferences_set_as_default_browser), trigger = listOf("I_AM_NOT_DEFAULT_BROWSER", "INACTIVE_2_DAYS"))),
      notificationConfig: NotificationConfig = NotificationConfig(refreshInterval = 120),
      onControl: ControlMessageBehavior = ControlMessageBehavior.SHOW_NEXT_MESSAGE,
      styles: Map<String, StyleData> = mapOf("DEFAULT" to StyleData(maxDisplayCount = 100, priority = 50), "EXPIRES_QUICKLY" to StyleData(maxDisplayCount = 1, priority = 100), "NOTIFICATION" to StyleData(maxDisplayCount = 1, priority = 50), "PERSISTENT" to StyleData(maxDisplayCount = 20, priority = 50), "SURVEY" to StyleData(maxDisplayCount = 10, priority = 55), "URGENT" to StyleData(maxDisplayCount = 10, priority = 100), "WARNING" to StyleData(maxDisplayCount = 10, priority = 60)),
      triggers: Map<String, String> = mapOf("ALWAYS" to "true", "DEVICE_ANDROID" to "os == 'Android'", "DEVICE_IOS" to "os == 'iOS'", "FUNNEL_ORGANIC" to "adjust_campaign == ''", "FUNNEL_PAID" to "adjust_campaign != ''", "FXA_NOT_SIGNED_IN" to "'sync_auth.sign_in'|eventLastSeen('Years', 0) > 4", "FXA_SIGNED_IN" to "'sync_auth.sign_in'|eventLastSeen('Years', 0) <= 4", "INACTIVE_1_DAY" to "'app_launched'|eventLastSeen('Hours') >= 24", "INACTIVE_2_DAYS" to "'app_launched'|eventLastSeen('Days', 0) >= 2", "INACTIVE_3_DAYS" to "'app_launched'|eventLastSeen('Days', 0) >= 3", "INACTIVE_4_DAYS" to "'app_launched'|eventLastSeen('Days', 0) >= 4", "INACTIVE_5_DAYS" to "'app_launched'|eventLastSeen('Days', 0) >= 5", "I_AM_DEFAULT_BROWSER" to "is_default_browser", "I_AM_NOT_DEFAULT_BROWSER" to "is_default_browser == false", "LAUNCHED_ONCE_THIS_WEEK" to "'app_launched'|eventSum('Days', 7) == 1", "NEVER" to "false", "USER_CASUAL" to "'app_launched'|eventCountNonZero('Days', 28) >= 7 && 'app_launched'|eventCountNonZero('Days', 28) < 14", "USER_CORE_ACTIVE" to "'app_launched'|eventCountNonZero('Days', 28) >= 21", "USER_DE_SPEAKER" to "'de' in locale", "USER_EN_SPEAKER" to "'en' in locale", "USER_ESTABLISHED_INSTALL" to "number_of_app_launches >=4", "USER_ES_SPEAKER" to "'es' in locale", "USER_FR_SPEAKER" to "'fr' in locale", "USER_INFREQUENT" to "'app_launched'|eventCountNonZero('Days', 28) >= 1 && 'app_launched'|eventCountNonZero('Days', 28) < 7", "USER_RECENTLY_INSTALLED" to "days_since_install < 7", "USER_RECENTLY_UPDATED" to "days_since_update < 7 && days_since_install != days_since_update", "USER_REGULAR" to "'app_launched'|eventCountNonZero('Days', 28) >= 14 && 'app_launched'|eventCountNonZero('Days', 28) < 21", "USER_TIER_ONE_COUNTRY" to "('US' in locale || 'GB' in locale || 'CA' in locale || 'DE' in locale || 'FR' in locale)")
   ) : this(
      _variables = _variables,
      _defaults = Defaults(actions = actions, messageUnderExperiment = messageUnderExperiment, messages = messages, notificationConfig = notificationConfig, onControl = onControl, styles = styles, triggers = triggers )
   )

   
   /** 
     * A growable map of action URLs.
     */
   val actions: Map<String, String> by lazy {
      _variables.getStringMap("actions")?.mergeWith(_defaults.actions) ?: _defaults.actions
   }

   /** 
     * Id or prefix of the message under experiment.
     */
   val messageUnderExperiment: String? by lazy {
      _variables.getString("message-under-experiment") ?: _defaults.messageUnderExperiment
   }

   /** 
     * A growable collection of messages
     */
   val messages: Map<String, MessageData> by lazy {
      _variables.getVariablesMap("messages")?.mapValuesNotNull(MessageData::create)?.mergeWith(_defaults.messages, MessageData::mergeWith) ?: _defaults.messages
   }

   /** 
     * Configuration of the notification worker for all notification messages.
     */
   val notificationConfig: NotificationConfig by lazy {
      _variables.getVariables("notification-config")?.let(NotificationConfig::create)?._mergeWith(_defaults.notificationConfig) ?: _defaults.notificationConfig
   }

   /** 
     * What should be displayed when a control message is selected.
     */
   val onControl: ControlMessageBehavior by lazy {
      _variables.getString("on-control")?.let(ControlMessageBehavior::enumValue) ?: _defaults.onControl
   }

   /** 
     * A map of styles to configure message appearance.
     * 
     */
   val styles: Map<String, StyleData> by lazy {
      _variables.getVariablesMap("styles")?.mapValuesNotNull(StyleData::create)?.mergeWith(_defaults.styles, StyleData::mergeWith) ?: _defaults.styles
   }

   /** 
     * A collection of out the box trigger expressions. Each entry maps to a
     * valid JEXL expression.
     * 
     */
   val triggers: Map<String, String> by lazy {
      _variables.getStringMap("triggers")?.mergeWith(_defaults.triggers) ?: _defaults.triggers
   }


}

/** 
 * A feature measuring campaign growth data
 */
public class GrowthData
    private constructor(
      private val _variables: Variables,
      private val _defaults: Defaults) {
   
   private data class Defaults(
      val enabled: Boolean
   )

   constructor(_variables: Variables = NullVariables.instance, 
      enabled: Boolean = false
   ) : this(
      _variables = _variables,
      _defaults = Defaults(enabled = enabled )
   )

   
   /** 
     * If true, the feature is active
     */
   val enabled: Boolean by lazy {
      _variables.getBool("enabled") ?: _defaults.enabled
   }


}



/** 
 * The types of onboarding panels in the onboarding page
 */
enum class OnboardingPanel {
    
    /** 
     * The themes onboarding panel where users pick themes
     */
    THEMES,
    /** 
     * The onboarding panel where users can choose their total cookie protection
     * settings
     */
    TCP,
    /** 
     * The onboarding panel where users can tap to view our privacy notice.
     */
    PRIVACY_NOTICE,
    /** 
     * The onboarding panel where users choose their toolbar placement (bottom
     * or top)
     */
    TOOLBAR_PLACEMENT,
    /** 
     * The onboarding panel where users can sign in to sync
     */
    SYNC;

    companion object {
        private val enumMap: Map<String, OnboardingPanel> by lazy {
            mapOf(
                "themes" to OnboardingPanel.THEMES,
                "tcp" to OnboardingPanel.TCP,
                "privacy-notice" to OnboardingPanel.PRIVACY_NOTICE,
                "toolbar-placement" to OnboardingPanel.TOOLBAR_PLACEMENT,
                "sync" to OnboardingPanel.SYNC)
        }

        fun enumValue(string: String): OnboardingPanel? = enumMap[string]
    }
}



/** 
 * The identity of a message surface
 */
enum class MessageSurfaceId {
    
    /** 
     * A local notification in the background, like a push notification.
     */
    NOTIFICATION,
    /** 
     * A banner in the homescreen.
     */
    HOMESCREEN;

    companion object {
        private val enumMap: Map<String, MessageSurfaceId> by lazy {
            mapOf(
                "notification" to MessageSurfaceId.NOTIFICATION,
                "homescreen" to MessageSurfaceId.HOMESCREEN)
        }

        fun enumValue(string: String): MessageSurfaceId? = enumMap[string]
    }
}



/** 
 * An enum to influence what should be displayed when a control message is
 * selected.
 */
enum class ControlMessageBehavior {
    
    /** 
     * The next eligible message should be shown.
     */
    SHOW_NEXT_MESSAGE,
    /** 
     * The surface should show no message.
     */
    SHOW_NONE;

    companion object {
        private val enumMap: Map<String, ControlMessageBehavior> by lazy {
            mapOf(
                "show-next-message" to ControlMessageBehavior.SHOW_NEXT_MESSAGE,
                "show-none" to ControlMessageBehavior.SHOW_NONE)
        }

        fun enumValue(string: String): ControlMessageBehavior? = enumMap[string]
    }
}



/** 
 * The identifiers for the sections of the MR 2022.
 */
enum class Mr2022Section {
    
    /** 
     * Home onboarding dialog for upgraded users.
     */
    HOME_ONBOARDING_DIALOG_EXISTING_USERS,
    /** 
     * CFR for the first time you see a synced tab on the home screen.
     */
    SYNC_CFR,
    /** 
     * CFR for the first time you use the browse with Total Cookie Protection on
     * the browser screen.
     */
    TCP_CFR,
    /** 
     * Controls the Total Cookie Protection feature.
     */
    TCP_FEATURE,
    /** 
     * Jump back-in onboarding message.
     */
    JUMP_BACK_IN_CFR,
    /** 
     * Wallpapers selection dialog tool for the home screen.
     */
    WALLPAPERS_SELECTION_TOOL;

    companion object {
        private val enumMap: Map<String, Mr2022Section> by lazy {
            mapOf(
                "home-onboarding-dialog-existing-users" to Mr2022Section.HOME_ONBOARDING_DIALOG_EXISTING_USERS,
                "sync-cfr" to Mr2022Section.SYNC_CFR,
                "tcp-cfr" to Mr2022Section.TCP_CFR,
                "tcp-feature" to Mr2022Section.TCP_FEATURE,
                "jump-back-in-cfr" to Mr2022Section.JUMP_BACK_IN_CFR,
                "wallpapers-selection-tool" to Mr2022Section.WALLPAPERS_SELECTION_TOOL)
        }

        fun enumValue(string: String): Mr2022Section? = enumMap[string]
    }
}



/** 
 * The identifiers for the sections of the MR 2022.
 */
enum class CookieBannersSection {
    
    /** 
     * An integer either 0 or 1 indicating if cookie banner setting should be
     * enabled or disabled, 0 for setting the value to disabled, 1  for enabling
     * the setting with the value reject_all.
     */
    FEATURE_SETTING_VALUE,
    /** 
     * An integer indicating the number of hours that needs to happen before
     * the re-engagement dialog shows again since the last seen, for example if
     * set to 4 that means if the users has seen the dialog, it will see it 4
     * hours later.
     */
    DIALOG_RE_ENGAGE_TIME,
    /** 
     * An integer from 0 to 2, indicating which text variant should be used on
     * the re-engagement dialog. 0 to indicate the variant control should be
     * used, 1 indicates the variant 1 should be used, 2 indicates the variant
     * 2 should be used, each variant can be found in the mockups for cookie
     * banner handling.
     */
    DIALOG_TEXT_VARIANT,
    /** 
     * An integer either 0 or 1 indicating if the UI for cookie banner handling
     * should be visible, 0 to hide the UI and 1 to show the UI. The actual UI
     * is composed by cookie banner section in the settings page, the toolbar
     * section and the re-engagement dialog.
     */
    FEATURE_UI;

    companion object {
        private val enumMap: Map<String, CookieBannersSection> by lazy {
            mapOf(
                "feature-setting-value" to CookieBannersSection.FEATURE_SETTING_VALUE,
                "dialog-re-engage-time" to CookieBannersSection.DIALOG_RE_ENGAGE_TIME,
                "dialog-text-variant" to CookieBannersSection.DIALOG_TEXT_VARIANT,
                "feature-ui" to CookieBannersSection.FEATURE_UI)
        }

        fun enumValue(string: String): CookieBannersSection? = enumMap[string]
    }
}



/** 
 * The identifiers for the sections of the homescreen.
 */
enum class HomeScreenSection {
    
    /** 
     * Subsection of the Pocket homescreen section which shows sponsored
     * stories.
     */
    POCKET_SPONSORED_STORIES,
    /** 
     * The tab groups
     */
    RECENT_EXPLORATIONS,
    /** 
     * The pocket section. This should only be available in the US.
     */
    POCKET,
    /** 
     * The sites the user has bookmarked recently.
     */
    RECENTLY_SAVED,
    /** 
     * The frecency and pinned sites.
     */
    TOP_SITES,
    /** 
     * The tabs the user was looking immediately before being interrupted.
     */
    JUMP_BACK_IN;

    companion object {
        private val enumMap: Map<String, HomeScreenSection> by lazy {
            mapOf(
                "pocket-sponsored-stories" to HomeScreenSection.POCKET_SPONSORED_STORIES,
                "recent-explorations" to HomeScreenSection.RECENT_EXPLORATIONS,
                "pocket" to HomeScreenSection.POCKET,
                "recently-saved" to HomeScreenSection.RECENTLY_SAVED,
                "top-sites" to HomeScreenSection.TOP_SITES,
                "jump-back-in" to HomeScreenSection.JUMP_BACK_IN)
        }

        fun enumValue(string: String): HomeScreenSection? = enumMap[string]
    }
}

/** 
 * Attributes controlling the global configuration of notification messages.
 */
public class NotificationConfig
    private constructor(
      private val _variables: Variables,
      private val _defaults: Defaults) {
   
   private data class Defaults(
      val refreshInterval: Int
   )

   constructor(_variables: Variables = NullVariables.instance, 
      refreshInterval: Int = 240
   ) : this(
      _variables = _variables,
      _defaults = Defaults(refreshInterval = refreshInterval )
   )

   
   /** 
     * How often, in minutes, the notification message worker will wake up and
     * check for new messages.
     * 
     */
   val refreshInterval: Int by lazy {
      _variables.getInt("refresh-interval") ?: _defaults.refreshInterval
   }



    internal fun _mergeWith(defaults: NotificationConfig?): NotificationConfig =
        defaults?.let { NotificationConfig(_variables = this._variables, _defaults = it._defaults) } ?: this

    companion object {
        internal fun create(variables: Variables): NotificationConfig? =
            NotificationConfig(_variables = variables)

        internal fun mergeWith(overrides: NotificationConfig, defaults: NotificationConfig): NotificationConfig =
            overrides._mergeWith(defaults)
    }
}

/** 
 * An object to describe a message. It uses human readable strings to describe
 * the triggers, action and style of the message as well as the text of the
 * message and call to action.
 * 
 */
public class MessageData
    private constructor(
      private val _variables: Variables,
      private val _defaults: Defaults) {
   
   private data class Defaults(
      val action: StringHolder,
      val buttonLabel: StringHolder?,
      val isControl: Boolean,
      val style: String,
      val surface: MessageSurfaceId,
      val text: StringHolder,
      val title: StringHolder?,
      val trigger: List<String>
   )

   constructor(_variables: Variables = NullVariables.instance, 
      action: StringHolder = Res.string(R.string.empty_string),
      buttonLabel: StringHolder? = null,
      isControl: Boolean = false,
      style: String = "DEFAULT",
      surface: MessageSurfaceId = MessageSurfaceId.HOMESCREEN,
      text: StringHolder = Res.string(R.string.empty_string),
      title: StringHolder? = null,
      trigger: List<String> = listOf()
   ) : this(
      _variables = _variables,
      _defaults = Defaults(action = action, buttonLabel = buttonLabel, isControl = isControl, style = style, surface = surface, text = text, title = title, trigger = trigger )
   )

   
   /** 
     * A URL of a page or a deeplink. This may have substitution variables in.
     * 
     */
   val action: String by lazy {
      _variables.getText("action") ?: _defaults.action.toString(_variables.context)
   }

   /** 
     * The text on the button. If no text is present, the whole message is
     * clickable.
     * 
     */
   val buttonLabel: String? by lazy {
      _variables.getText("button-label") ?: _defaults.buttonLabel?.let { it.toString(_variables.context) }
   }

   /** 
     * Indicates if this message is the control message, if true shouldn't be
     * displayed
     */
   val isControl: Boolean by lazy {
      _variables.getBool("is-control") ?: _defaults.isControl
   }

   /** 
     * The style as described in a `StyleData` from the styles table.
     * 
     */
   val style: String by lazy {
      _variables.getString("style") ?: _defaults.style
   }

   /** 
     * The surface identifier for this message.
     */
   val surface: MessageSurfaceId by lazy {
      _variables.getString("surface")?.let(MessageSurfaceId::enumValue) ?: _defaults.surface
   }

   /** 
     * The message text displayed to the user
     */
   val text: String by lazy {
      _variables.getText("text") ?: _defaults.text.toString(_variables.context)
   }

   /** 
     * The title text displayed to the user
     */
   val title: String? by lazy {
      _variables.getText("title") ?: _defaults.title?.let { it.toString(_variables.context) }
   }

   /** 
     * A list of strings corresponding to targeting expressions. The message
     * will be shown if all expressions `true`.
     * 
     */
   val trigger: List<String> by lazy {
      _variables.getStringList("trigger") ?: _defaults.trigger
   }



    internal fun _mergeWith(defaults: MessageData?): MessageData =
        defaults?.let { MessageData(_variables = this._variables, _defaults = it._defaults) } ?: this

    companion object {
        internal fun create(variables: Variables): MessageData? =
            MessageData(_variables = variables)

        internal fun mergeWith(overrides: MessageData, defaults: MessageData): MessageData =
            overrides._mergeWith(defaults)
    }
}

/** 
 * A group of properties (predominantly visual) to describe the style of the
 * message.
 * 
 */
public class StyleData
    private constructor(
      private val _variables: Variables,
      private val _defaults: Defaults) {
   
   private data class Defaults(
      val maxDisplayCount: Int,
      val priority: Int
   )

   constructor(_variables: Variables = NullVariables.instance, 
      maxDisplayCount: Int = 5,
      priority: Int = 50
   ) : this(
      _variables = _variables,
      _defaults = Defaults(maxDisplayCount = maxDisplayCount, priority = priority )
   )

   
   /** 
     * How many sessions will this message be shown to the user before it is
     * expired.
     * 
     */
   val maxDisplayCount: Int by lazy {
      _variables.getInt("max-display-count") ?: _defaults.maxDisplayCount
   }

   /** 
     * The importance of this message. 0 is not very important, 100 is very
     * important.
     * 
     */
   val priority: Int by lazy {
      _variables.getInt("priority") ?: _defaults.priority
   }



    internal fun _mergeWith(defaults: StyleData?): StyleData =
        defaults?.let { StyleData(_variables = this._variables, _defaults = it._defaults) } ?: this

    companion object {
        internal fun create(variables: Variables): StyleData? =
            StyleData(_variables = variables)

        internal fun mergeWith(overrides: StyleData, defaults: StyleData): StyleData =
            overrides._mergeWith(defaults)
    }
}

